




.build/leonardo/src/KnightRider.cpp : src/KnightRider.ino
	@mkdir -p .build/leonardo/src
	@echo [93msrc/KnightRider.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/leonardo/src/KnightRider.cpp
	@true

